keys:
  # Users
  - &users:
    - &david f150e9ccdfbcd5534edc573d0e3d78eeaa6c35c5
  # Hosts
  - &hosts:
    - &mgt1 age16nj8s2cxs7d66eehxqltg93gddp9xu7mydztyv6mz3a024eaqycq4gc2p6


creation_rules:
  - path_regex: hosts/common/secrets.ya?ml$
    key_groups:
    - age:
      - *mgt1
      pgp:
      - *david